-- The Raven
-- Generated by epub2badge.py for the OnionDAO badge EPUB reader.
-- RIGHT/DOWN next page, LEFT/UP previous, SELECT chapters, CANCEL exit.
BOOK = {
    title = "The Raven",
    label = "The Raven",
    id = "726a2c",
    part = 1,
    parts = 1,
    layout = { x = 3, y = 14, lh = 16, rows = 8, rule = 140, foot = 165 },
    chapters = {
        { p = 8, t = "The Raven" },
        { p = 58, t = "THE FULL PROJECT GUTE" },
    },
    pages = {
[==[
 The Project Gutenberg
   eBook of The Raven

  This eBook is for the
use of anyone anywhere
in the United States
and most other parts of
the world at no cost]==],
[==[
and with almost no
restrictions
whatsoever. You may
copy it, give it away
or re-use it under the
terms of the Project
Gutenberg License
included with this]==],
[==[
eBook or online at
www.gutenberg.org. If
you are not located in
the United States, you
will have to check the
laws of the country
where you are located
before using this]==],
[==[
eBook.
  Title: The Raven
  Author: Edgar Allan
Poe
  Release date: October
1, 1997 [eBook #1065]
Most recently updated:
October 29, 2024]==],
[==[
  Language: English
  Other information and
formats: www.gutenberg.
org/ebooks/1065
  Credits: Levent
Kurnaz. HTML version by
Al Haines.
  *** START OF THE]==],
[==[
PROJECT GUTENBERG EBOOK
THE RAVEN ***
  THIS EBOOK WAS ONE OF
PROJECT GUTENBERG'S
EARLY FILES. THERE IS
AN IMPROVED ILLUSTRATED
EDITION OF THIS TITLE
WHICH MAY VIEWED AT]==],
[==[
EBOOK [ #45484 ]]==],
[==[
       The Raven


   by Edgar Allan Poe

  Once upon a midnight
dreary, while I
pondered, weak and]==],
[==[
weary,
Over many a quaint and
curious volume of
forgotten lore--
While I nodded, nearly
napping, suddenly there
came a tapping,
As of some one gently]==],
[==[
rapping, rapping at my
chamber door.
"'Tis some visiter," I
muttered, "tapping at
my chamber door--
Only this and nothing
more."
  Ah, distinctly I]==],
[==[
remember it was in the
bleak December,
And each separate dying
ember wrought its ghost
upon the floor.
Eagerly I wished the
morrow;--vainly I had
sought to borrow]==],
[==[
From my books surcease
of sorrow--sorrow for
the lost Lenore--
For the rare and
radiant maiden whom the
angels name Lenore--
Nameless here for
evermore.]==],
[==[
  And the silken sad
uncertain rustling of
each purple curtain
Thrilled me--filled me
with fantastic terrors
never felt before;
So that now, to still
the beating of my]==],
[==[
heart, I stood
repeating
"'Tis some visiter
entreating entrance at
my chamber door--
Some late visiter
entreating entrance at
my chamber door;]==],
[==[
This it is and nothing
more."
  Presently my soul
grew stronger;
hesitating then no
longer,
"Sir," said I, "or
Madam, truly your]==],
[==[
forgiveness I implore;
But the fact is I was
napping, and so gently
you came rapping,
And so faintly you came
tapping, tapping at my
chamber door,
That I scarce was sure]==],
[==[
I heard you"--here I
opened wide the door--
Darkness there and
nothing more.
  Deep into that
darkness peering, long
I stood there
wondering, fearing,]==],
[==[
Doubting, dreaming
dreams no mortals ever
dared to dream before;
But the silence was
unbroken, and the
stillness gave no
token,
And the only word there]==],
[==[
spoken was the
whispered word,
"Lenore?"
This I whispered, and
an echo murmured back
the word, "Lenore!"--
Merely this and nothing
more.]==],
[==[
  Back into the chamber
turning, all my soul
within me burning,
Soon again I heard a
tapping something
louder than before.
"Surely," said I,
"surely that is]==],
[==[
something at my window
lattice;
Let me see, then, what
thereat is and this
mystery explore--
Let my heart be still a
moment and this mystery
explore;--]==],
[==[
'Tis the wind and
nothing more."
  Open here I flung the
shutter, when, with
many a flirt and
flutter,
In there stepped a
stately Raven of the]==],
[==[
saintly days of yore.
Not the least obeisance
made he; not a minute
stopped or stayed he,
But, with mien of lord
or lady, perched above
my chamber door--
Perched upon a bust of]==],
[==[
Pallas just above my
chamber door--
Perched, and sat, and
nothing more.
  Then the ebony bird
beguiling my sad fancy
into smiling,
By the grave and stern]==],
[==[
decorum of the
countenance it wore,
"Though thy crest be
shorn and shaven,
thou," I said, "art
sure no craven,
Ghastly grim and
ancient Raven wandering]==],
[==[
from the Nightly
shore--
Tell me what thy lordly
name is on the Night's
Plutonian shore!"
Quoth the Raven,
"Nevermore."
  Much I marvelled this]==],
[==[
ungainly fowl to hear
discourse so plainly,
Though its answer
little meaning--little
relevancy bore;
For we cannot help
agreeing that no living
human being]==],
[==[
Ever yet was blessed
with seeing bird above
his chamber door--
Bird or beast upon the
sculptured bust above
his chamber door,
With such name as
"Nevermore."]==],
[==[
  But the Raven,
sitting lonely on that
placid bust, spoke only
That one word, as if
its soul in that one
word he did outpour
Nothing farther then he
uttered; not a feather]==],
[==[
then he fluttered--
Till I scarcely more
than muttered: "Other
friends have flown
before--
On the morrow he will
leave me, as my Hopes
have flown before."]==],
[==[
Then the bird said
"Nevermore."
  Startled at the
stillness broken by
reply so aptly spoken,
"Doubtless," said I,
"what it utters is its
only stock and store,]==],
[==[
Caught from some
unhappy master whom
unmerciful Disaster
Followed fast and
followed faster till
his songs one burden
bore--
Till the dirges of his]==],
[==[
Hope that melancholy
burden bore
Of 'Never--nevermore.'"
  But the Raven still
beguiling all my sad
soul into smiling,
Straight I wheeled a
cushioned seat in front]==],
[==[
of bird and bust and
door;
Then, upon the velvet
sinking, I betook
myself to linking
Fancy unto fancy,
thinking what this
ominous bird of yore--]==],
[==[
What this grim,
ungainly, ghastly,
gaunt, and ominous bird
of yore
Meant in croaking
"Nevermore."
  This I sat engaged in
guessing, but no]==],
[==[
syllable expressing
To the fowl whose fiery
eyes now burned into my
bosom's core;
This and more I sat
divining, with my head
at ease reclining
On the cushion's velvet]==],
[==[
lining that the lamp-
light gloated o'er,
But whose velvet violet
lining with the lamp-
light gloating o'er
She shall press, ah,
nevermore!
  Then, methought, the]==],
[==[
air grew denser,
perfumed from an unseen
censer
Swung by Seraphim whose
foot-falls tinkled on
the tufted floor.
"Wretch," I cried, "thy
God hath lent thee--by]==],
[==[
these angels he hath
sent thee
Respite--respite and
nepenthe from thy
memories of Lenore!
Quaff, oh quaff this
kind nepenthe and
forget this lost]==],
[==[
Lenore!"
Quoth the Raven,
"Nevermore."
  "Prophet!" said I,
"thing of evil!--
prophet still, if bird
or devil!--
Whether Tempter sent,]==],
[==[
or whether tempest
tossed thee here
ashore,
Desolate, yet all
undaunted, on this
desert land enchanted--
On this home by Horror
haunted--tell me truly,]==],
[==[
I implore--
Is there--is there balm
in Gilead?--tell me--
tell me, I implore!"
Quoth the Raven,
"Nevermore."
  "Prophet!" said I,
"thing of evil!--]==],
[==[
prophet still, if bird
or devil!
By that Heaven that
bends above us--by that
God we both adore--
Tell this soul with
sorrow laden if, within
the distant Aidenn,]==],
[==[
It shall clasp a
sainted maiden whom the
angels name Lenore--
Clasp a rare and
radiant maiden whom the
angels name Lenore."
Quoth the Raven,
"Nevermore."]==],
[==[
  "Be that our sign of
parting, bird or
fiend!" I shrieked,
upstarting--
"Get thee back into the
tempest and the Night's
Plutonian shore!
Leave no black plume as]==],
[==[
a token of that lie thy
soul has spoken!
Leave my loneliness
unbroken!--quit the
bust above my door!
Take thy beak from out
my heart, and take thy
form from off my door!"]==],
[==[
Quoth the Raven,
"Nevermore."
  And the Raven, never
flitting, still is
sitting, still is
sitting
On the pallid bust of
Pallas just above my]==],
[==[
chamber door;
And his eyes have all
the seeming of a
demon's that is
dreaming
And the lamp-light o'er
him streaming throws
his shadows on the]==],
[==[
floor;
And my soul from out
that shadow that lies
floating on the floor
Shall be lifted--
nevermore!
  *** END OF THE
PROJECT GUTENBERG EBOOK]==],
[==[
THE RAVEN ***
  Updated editions will
replace the previous
one--the old editions
will be renamed.
  Creating the works
from print editions not
protected by U.S.]==],
[==[
copyright law means
that no one owns a
United States copyright
in these works, so the
Foundation (and you!)
can copy and distribute
it in the United States
without permission and]==],
[==[
without paying
copyright royalties.
Special rules, set
forth in the General
Terms of Use part of
this license, apply to
copying and
distributing Project]==],
[==[
GutenbergTM electronic
works to protect the
PROJECT GUTENBERGTM
concept and trademark.
Project Gutenberg is a
registered trademark,
and may not be used if
you charge for an]==],
[==[
eBook, except by
following the terms of
the trademark license,
including paying
royalties for use of
the Project Gutenberg
trademark. If you do
not charge anything for]==],
[==[
copies of this eBook,
complying with the
trademark license is
very easy. You may use
this eBook for nearly
any purpose such as
creation of derivative
works, reports,]==],
[==[
performances and
research. Project
Gutenberg eBooks may be
modified and printed
and given away--you may
do practically ANYTHING
in the United States
with eBooks not]==],
[==[
protected by U.S.
copyright law.
Redistribution is
subject to the
trademark license,
especially commercial
redistribution.
  START: FULL LICENSE]==],
[==[
    THE FULL PROJECT
  GUTENBERGTM LICENSE

  PLEASE READ THIS
BEFORE YOU DISTRIBUTE
OR USE THIS WORK
  To protect the
Project GutenbergTM]==],
[==[
mission of promoting
the free distribution
of electronic works, by
using or distributing
this work (or any other
work associated in any
way with the phrase
"Project Gutenberg"),]==],
[==[
you agree to comply
with all the terms of
the Full Project
Gutenberg License
available with this
file or online at www.g
utenberg.org/license.
  Section 1. General]==],
[==[
Terms of Use and
Redistributing Project
Gutenberg electronic
works
  1.A. By reading or
using any part of this
Project Gutenberg
electronic work, you]==],
[==[
indicate that you have
read, understand, agree
to and accept all the
terms of this license
and intellectual
property
(trademark/copyright)
agreement. If you do]==],
[==[
not agree to abide by
all the terms of this
agreement, you must
cease using and return
or destroy all copies
of Project Gutenberg
electronic works in
your possession. If you]==],
[==[
paid a fee for
obtaining a copy of or
access to a Project
Gutenberg electronic
work and you do not
agree to be bound by
the terms of this
agreement, you may]==],
[==[
obtain a refund from
the person or entity to
whom you paid the fee
as set forth in
paragraph 1.E.8.
  1.B. "Project
Gutenberg" is a
registered trademark.]==],
[==[
It may only be used on
or associated in any
way with an electronic
work by people who
agree to be bound by
the terms of this
agreement. There are a
few things that you can]==],
[==[
do with most Project
Gutenberg electronic
works even without
complying with the full
terms of this
agreement. See
paragraph 1.C below.
There are a lot of]==],
[==[
things you can do with
Project Gutenberg
electronic works if you
follow the terms of
this agreement and help
preserve free future
access to Project
Gutenberg electronic]==],
[==[
works. See paragraph
1.E below.
  1.C. The Project
Gutenberg Literary
Archive Foundation
("the Foundation" or
PGLAF), owns a
compilation copyright]==],
[==[
in the collection of
Project Gutenberg
electronic works.
Nearly all the
individual works in the
collection are in the
public domain in the
United States. If an]==],
[==[
individual work is
unprotected by
copyright law in the
United States and you
are located in the
United States, we do
not claim a right to
prevent you from]==],
[==[
copying, distributing,
performing, displaying
or creating derivative
works based on the work
as long as all
references to Project
Gutenberg are removed.
Of course, we hope that]==],
[==[
you will support the
Project Gutenberg
mission of promoting
free access to
electronic works by
freely sharing Project
Gutenberg works in
compliance with the]==],
[==[
terms of this agreement
for keeping the Project
Gutenberg name
associated with the
work. You can easily
comply with the terms
of this agreement by
keeping this work in]==],
[==[
the same format with
its attached full
Project Gutenberg
License when you share
it without charge with
others.
  1.D. The copyright
laws of the place where]==],
[==[
you are located also
govern what you can do
with this work.
Copyright laws in most
countries are in a
constant state of
change. If you are
outside the United]==],
[==[
States, check the laws
of your country in
addition to the terms
of this agreement
before downloading,
copying, displaying,
performing,
distributing or]==],
[==[
creating derivative
works based on this
work or any other
Project Gutenberg work.
The Foundation makes no
representations
concerning the
copyright status of any]==],
[==[
work in any country
other than the United
States.
  1.E. Unless you have
removed all references
to Project Gutenberg:
  1.E.1. The following
sentence, with active]==],
[==[
links to, or other
immediate access to,
the full Project
Gutenberg License must
appear prominently
whenever any copy of a
Project Gutenberg work
(any work on which the]==],
[==[
phrase "Project
Gutenberg" appears, or
with which the phrase
"Project Gutenberg" is
associated) is
accessed, displayed,
performed, viewed,
copied or distributed:]==],
[==[
  This eBook is for the
use of anyone anywhere
in the United States
and most other parts of
the world at no cost
and with almost no
restrictions
whatsoever. You may]==],
[==[
copy it, give it away
or re-use it under the
terms of the Project
GutenbergTM License
included with this
eBook or online at
www.gutenberg.org. If
you are not located in]==],
[==[
the United States, you
will have to check the
laws of the country
where you are located
before using this
eBook.
  1.E.2. If an
individual Project]==],
[==[
Gutenberg electronic
work is derived from
texts not protected by
U.S. copyright law
(does not contain a
notice indicating that
it is posted with
permission of the]==],
[==[
copyright holder), the
work can be copied and
distributed to anyone
in the United States
without paying any fees
or charges. If you are
redistributing or
providing access to a]==],
[==[
work with the phrase
"Project Gutenberg"
associated with or
appearing on the work,
you must comply either
with the requirements
of paragraphs 1.E.1
through 1.E.7 or obtain]==],
[==[
permission for the use
of the work and the
Project Gutenberg
trademark as set forth
in paragraphs 1.E.8 or
1.E.9.
  1.E.3. If an
individual Project]==],
[==[
Gutenberg electronic
work is posted with the
permission of the
copyright holder, your
use and distribution
must comply with both
paragraphs 1.E.1
through 1.E.7 and any]==],
[==[
additional terms
imposed by the
copyright holder.
Additional terms will
be linked to the
Project Gutenberg
License for all works
posted with the]==],
[==[
permission of the
copyright holder found
at the beginning of
this work.
  1.E.4. Do not unlink
or detach or remove the
full Project Gutenberg
License terms from this]==],
[==[
work, or any files
containing a part of
this work or any other
work associated with
Project Gutenberg.
  1.E.5. Do not copy,
display, perform,
distribute or]==],
[==[
redistribute this
electronic work, or any
part of this electronic
work, without
prominently displaying
the sentence set forth
in paragraph 1.E.1 with
active links or]==],
[==[
immediate access to the
full terms of the
Project Gutenberg
License.
  1.E.6. You may
convert to and
distribute this work in
any binary, compressed,]==],
[==[
marked up,
nonproprietary or
proprietary form,
including any word
processing or hypertext
form. However, if you
provide access to or
distribute copies of a]==],
[==[
Project Gutenberg work
in a format other than
"Plain Vanilla ASCII"
or other format used in
the official version
posted on the official
Project Gutenberg
website]==],
[==[
(www.gutenberg.org),
you must, at no
additional cost, fee or
expense to the user,
provide a copy, a means
of exporting a copy, or
a means of obtaining a
copy upon request, of]==],
[==[
the work in its
original "Plain Vanilla
ASCII" or other form.
Any alternate format
must include the full
Project Gutenberg
License as specified in
paragraph 1.E.1.]==],
[==[
  1.E.7. Do not charge
a fee for access to,
viewing, displaying,
performing, copying or
distributing any
Project Gutenberg works
unless you comply with
paragraph 1.E.8 or]==],
[==[
1.E.9.
  1.E.8. You may charge
a reasonable fee for
copies of or providing
access to or
distributing Project
Gutenberg electronic
works provided that:]==],
[==[
  - * You pay a royalty
fee of 20% of the gross
profits you derive from
the use of Project
Gutenberg works
calculated using the
method you already use
to calculate your]==],
[==[
applicable taxes. The
fee is owed to the
owner of the Project
Gutenberg trademark,
but he has agreed to
donate royalties under
this paragraph to the
Project Gutenberg]==],
[==[
Literary Archive
Foundation. Royalty
payments must be paid
within 60 days
following each date on
which you prepare (or
are legally required to
prepare) your periodic]==],
[==[
tax returns. Royalty
payments should be
clearly marked as such
and sent to the Project
Gutenberg Literary
Archive Foundation at
the address specified
in Section 4,]==],
[==[
"Information about
donations to the
Project Gutenberg
Literary Archive
Foundation."
  - * You provide a
full refund of any
money paid by a user]==],
[==[
who notifies you in
writing (or by e-mail)
within 30 days of
receipt that s/he does
not agree to the terms
of the full Project
GutenbergTM License.
You must require such a]==],
[==[
user to return or
destroy all copies of
the works possessed in
a physical medium and
discontinue all use of
and all access to other
copies of Project
GutenbergTM works.]==],
[==[
  - * You provide, in
accordance with
paragraph 1.F.3, a full
refund of any money
paid for a work or a
replacement copy, if a
defect in the
electronic work is]==],
[==[
discovered and reported
to you within 90 days
of receipt of the work.
  - * You comply with
all other terms of this
agreement for free
distribution of Project
GutenbergTM works.]==],
[==[
  1.E.9. If you wish to
charge a fee or
distribute a Project
GutenbergTM electronic
work or group of works
on different terms than
are set forth in this
agreement, you must]==],
[==[
obtain permission in
writing from the
Project Gutenberg
Literary Archive
Foundation, the manager
of the Project
GutenbergTM trademark.
Contact the Foundation]==],
[==[
as set forth in Section
3 below.
  1.F.
  1.F.1. Project
Gutenberg volunteers
and employees expend
considerable effort to
identify, do copyright]==],
[==[
research on, transcribe
and proofread works not
protected by U.S.
copyright law in
creating the Project
GutenbergTM collection.
Despite these efforts,
Project GutenbergTM]==],
[==[
electronic works, and
the medium on which
they may be stored, may
contain "Defects," such
as, but not limited to,
incomplete, inaccurate
or corrupt data,
transcription errors, a]==],
[==[
copyright or other
intellectual property
infringement, a
defective or damaged
disk or other medium, a
computer virus, or
computer codes that
damage or cannot be]==],
[==[
read by your equipment.
  1.F.2. LIMITED
WARRANTY, DISCLAIMER OF
DAMAGES - Except for
the "Right of
Replacement or Refund"
described in paragraph
1.F.3, the Project]==],
[==[
Gutenberg Literary
Archive Foundation, the
owner of the Project
GutenbergTM trademark,
and any other party
distributing a Project
GutenbergTM electronic
work under this]==],
[==[
agreement, disclaim all
liability to you for
damages, costs and
expenses, including
legal fees. YOU AGREE
THAT YOU HAVE NO
REMEDIES FOR
NEGLIGENCE, STRICT]==],
[==[
LIABILITY, BREACH OF
WARRANTY OR BREACH OF
CONTRACT EXCEPT THOSE
PROVIDED IN PARAGRAPH
1.F.3. YOU AGREE THAT
THE FOUNDATION, THE
TRADEMARK OWNER, AND
ANY DISTRIBUTOR UNDER]==],
[==[
THIS AGREEMENT WILL NOT
BE LIABLE TO YOU FOR
ACTUAL, DIRECT,
INDIRECT,
CONSEQUENTIAL, PUNITIVE
OR INCIDENTAL DAMAGES
EVEN IF YOU GIVE NOTICE
OF THE POSSIBILITY OF]==],
[==[
SUCH DAMAGE.
  1.F.3. LIMITED RIGHT
OF REPLACEMENT OR
REFUND - If you
discover a defect in
this electronic work
within 90 days of
receiving it, you can]==],
[==[
receive a refund of the
money (if any) you paid
for it by sending a
written explanation to
the person you received
the work from. If you
received the work on a
physical medium, you]==],
[==[
must return the medium
with your written
explanation. The person
or entity that provided
you with the defective
work may elect to
provide a replacement
copy in lieu of a]==],
[==[
refund. If you received
the work
electronically, the
person or entity
providing it to you may
choose to give you a
second opportunity to
receive the work]==],
[==[
electronically in lieu
of a refund. If the
second copy is also
defective, you may
demand a refund in
writing without further
opportunities to fix
the problem.]==],
[==[
  1.F.4. Except for the
limited right of
replacement or refund
set forth in paragraph
1.F.3, this work is
provided to you 'AS-
IS', WITH NO OTHER
WARRANTIES OF ANY KIND,]==],
[==[
EXPRESS OR IMPLIED,
INCLUDING BUT NOT
LIMITED TO WARRANTIES
OF MERCHANTABILITY OR
FITNESS FOR ANY
PURPOSE.
  1.F.5. Some states do
not allow disclaimers]==],
[==[
of certain implied
warranties or the
exclusion or limitation
of certain types of
damages. If any
disclaimer or
limitation set forth in
this agreement violates]==],
[==[
the law of the state
applicable to this
agreement, the
agreement shall be
interpreted to make the
maximum disclaimer or
limitation permitted by
the applicable state]==],
[==[
law. The invalidity or
unenforceability of any
provision of this
agreement shall not
void the remaining
provisions.
  1.F.6. INDEMNITY -
You agree to indemnify]==],
[==[
and hold the
Foundation, the
trademark owner, any
agent or employee of
the Foundation, anyone
providing copies of
Project GutenbergTM
electronic works in]==],
[==[
accordance with this
agreement, and any
volunteers associated
with the production,
promotion and
distribution of Project
GutenbergTM electronic
works, harmless from]==],
[==[
all liability, costs
and expenses, including
legal fees, that arise
directly or indirectly
from any of the
following which you do
or cause to occur: (a)
distribution of this or]==],
[==[
any Project Gutenberg
work, (b) alteration,
modification, or
additions or deletions
to any Project
Gutenberg work, and (c)
any Defect you cause.
  Section 2.]==],
[==[
Information about the
Mission of Project
Gutenberg
  Project Gutenberg is
synonymous with the
free distribution of
electronic works in
formats readable by the]==],
[==[
widest variety of
computers including
obsolete, old, middle-
aged and new computers.
It exists because of
the efforts of hundreds
of volunteers and
donations from people]==],
[==[
in all walks of life.
  Volunteers and
financial support to
provide volunteers with
the assistance they
need are critical to
reaching Project
Gutenberg's goals and]==],
[==[
ensuring that the
Project Gutenberg
collection will remain
freely available for
generations to come. In
2001, the Project
Gutenberg Literary
Archive Foundation was]==],
[==[
created to provide a
secure and permanent
future for Project
Gutenberg and future
generations. To learn
more about the Project
Gutenberg Literary
Archive Foundation and]==],
[==[
how your efforts and
donations can help, see
Sections 3 and 4 and
the Foundation
information page at
www.gutenberg.org.
  Section 3.
Information about the]==],
[==[
Project Gutenberg
Literary Archive
Foundation
  The Project Gutenberg
Literary Archive
Foundation is a non-
profit 501(c)(3)
educational corporation]==],
[==[
organized under the
laws of the state of
Mississippi and granted
tax exempt status by
the Internal Revenue
Service. The
Foundation's EIN or
federal tax]==],
[==[
identification number
is 64-6221541.
Contributions to the
Project Gutenberg
Literary Archive
Foundation are tax
deductible to the full
extent permitted by]==],
[==[
U.S. federal laws and
your state's laws.
  The Foundation's
business office is
located at 41 Watchung
Plaza #516, Montclair
NJ 07042, USA, +1 (862)
621-9288. Email contact]==],
[==[
links and up to date
contact information can
be found at the
Foundation's website
and official page at ww
w.gutenberg.org/contact
  Section 4.
Information about]==],
[==[
Donations to the
Project Gutenberg
Literary Archive
Foundation
  Project GutenbergTM
depends upon and cannot
survive without
widespread public]==],
[==[
support and donations
to carry out its
mission of increasing
the number of public
domain and licensed
works that can be
freely distributed in
machine-readable form]==],
[==[
accessible by the
widest array of
equipment including
outdated equipment.
Many small donations
($1 to $5,000) are
particularly important
to maintaining tax]==],
[==[
exempt status with the
IRS.
  The Foundation is
committed to complying
with the laws
regulating charities
and charitable
donations in all 50]==],
[==[
states of the United
States. Compliance
requirements are not
uniform and it takes a
considerable effort,
much paperwork and many
fees to meet and keep
up with these]==],
[==[
requirements. We do not
solicit donations in
locations where we have
not received written
confirmation of
compliance. To SEND
DONATIONS or determine
the status of]==],
[==[
compliance for any
particular state visit
www.gutenberg.org/donat
e.
  While we cannot and
do not solicit
contributions from
states where we have]==],
[==[
not met the
solicitation
requirements, we know
of no prohibition
against accepting
unsolicited donations
from donors in such
states who approach us]==],
[==[
with offers to donate.
  International
donations are
gratefully accepted,
but we cannot make any
statements concerning
tax treatment of
donations received from]==],
[==[
outside the United
States. U.S. laws alone
swamp our small staff.
  Please check the
Project Gutenberg web
pages for current
donation methods and
addresses. Donations]==],
[==[
are accepted in a
number of other ways
including checks,
online payments and
credit card donations.
To donate, please
visit: www.gutenberg.or
g/donate.]==],
[==[
  Section 5. General
Information About
Project Gutenberg
electronic works
  Professor Michael S.
Hart was the originator
of the Project
Gutenberg concept of a]==],
[==[
library of electronic
works that could be
freely shared with
anyone. For forty
years, he produced and
distributed Project
Gutenberg eBooks with
only a loose network of]==],
[==[
volunteer support.
  Project Gutenberg
eBooks are often
created from several
printed editions, all
of which are confirmed
as not protected by
copyright in the U.S.]==],
[==[
unless a copyright
notice is included.
Thus, we do not
necessarily keep eBooks
in compliance with any
particular paper
edition.
  Most people start at]==],
[==[
our website which has
the main PG search
facility:
www.gutenberg.org.
  This website includes
information about
Project Gutenberg,
including how to make]==],
[==[
donations to the
Project Gutenberg
Literary Archive
Foundation, how to help
produce our new eBooks,
and how to subscribe to
our email newsletter to
hear about new eBooks.]==],
[==[

         * * *

        THE END]==],
    },
}

-- EPUB reader runtime for Onion OS.
--
-- This file is not run directly: epub2badge.py prepends a generated
-- `BOOK = { ... }` table (title, layout, chapters, pages) and installs the
-- combined script on the badge. See README.md in this folder.
--
-- Controls:
--   RIGHT/DOWN: next page (hold to keep turning)
--   LEFT/UP: previous page (hold to keep turning)
--   SELECT: chapter menu (UP/DOWN move, SELECT jump, CANCEL back)
--   CANCEL: save bookmark and return to Onion OS
--
-- Page turns are drawn as two deferred-frame commits — the text band and the
-- footer band — so each dirty region stays under the firmware's 75% partial
-- refresh threshold. That keeps a turn at ~2 fast partial refreshes instead
-- of one ~1.7 s full-flash refresh. The firmware still forces a ghost-clearing
-- full refresh every 30 partials.

local B = BOOK

local size = onion.display_size()
local W, H = size.width, size.height

local TEXT_X = B.layout.x
local TEXT_Y = B.layout.y
local LINE_H = B.layout.lh
local RULE_Y = B.layout.rule
local FOOT_Y = B.layout.foot

local CHAR_W = 11 -- FreeMono9pt7b advance
local HOLD_MS = 600
local REPEAT_MS = 350
local SAVE_AFTER_MS = 2000

local pages = B.pages
local total = #pages
local bookmark_key = "bk_" .. B.id .. "_" .. B.part

if total == 0 then
    onion.log("Book has no pages")
    onion.release_display()
    return
end

local page = tonumber(onion.kv_get(bookmark_key) or "") or 1
if page < 1 then page = 1 end
if page > total then page = total end

local dirty = false
local dirty_at = 0

local function save_bookmark()
    if not dirty then return end
    local ok, err = onion.kv_set(bookmark_key, tostring(page))
    if not ok and err then onion.log("Bookmark: " .. err) end
    dirty = false
end

local function footer_right()
    local pct = math.floor(page * 100 / total)
    return page .. "/" .. total .. " " .. pct .. "%"
end

-- Footer band only: blank below the rule, then label + progress. Caller wraps
-- this in display_begin/commit.
local function draw_footer()
    onion.display_rect(0, RULE_Y + 1, W, H - RULE_Y - 1,
        { fill = true, color = "white", clear = false })
    local right = footer_right()
    local right_x = W - 3 - #right * CHAR_W
    local label_max = math.floor((right_x - 8) / CHAR_W)
    local label = string.sub(B.label, 1, label_max)
    onion.display_text(label, TEXT_X, FOOT_Y, { clear = false })
    onion.display_text(right, right_x, FOOT_Y, { clear = false })
end

-- full=true redraws the whole screen in one commit (used for the first page
-- and when returning from the menu, where a full refresh happens anyway).
-- full=false splits text and footer into two commits to stay partial.
local function draw_page(full)
    onion.display_begin()
    if full then
        onion.display_rect(0, 0, W, H, { fill = true, color = "white", clear = false })
    else
        onion.display_rect(0, 0, W, RULE_Y - 1, { fill = true, color = "white", clear = false })
    end
    onion.display_lines(pages[page], TEXT_X, TEXT_Y, LINE_H, { clear = false })
    if full then
        onion.display_line(0, RULE_Y, W - 1, RULE_Y, false)
        draw_footer()
        onion.display_commit()
    else
        onion.display_commit()
        onion.display_begin()
        draw_footer()
        onion.display_commit()
    end
end

local function turn(delta)
    local target = page + delta
    if target < 1 or target > total then return end
    page = target
    dirty = true
    dirty_at = onion.millis()
    draw_page(false)
end

-- Chapter menu -------------------------------------------------------------

local MENU_ROWS = 6

local function menu_entries()
    local entries = { { t = "Resume", p = page } }
    for i = 1, #B.chapters do
        local c = B.chapters[i]
        entries[#entries + 1] = { t = c.t, p = c.p }
    end
    return entries
end

local function draw_menu(entries, cursor, top)
    onion.display_begin()
    onion.display_rect(0, 0, W, H, { fill = true, color = "white", clear = false })
    onion.display_text(string.sub(B.title, 1, 21), 3, 16, { clear = false, font = "bold" })
    onion.display_text("Page " .. footer_right(), 3, 34, { clear = false })
    onion.display_line(0, 40, W - 1, 40, false)
    local lines = {}
    for row = 1, MENU_ROWS do
        local i = top + row - 1
        if i > #entries then break end
        local prefix = (i == cursor) and "> " or "  "
        lines[#lines + 1] = prefix .. string.sub(entries[i].t, 1, 21)
    end
    onion.display_lines(lines, 3, 56, 18, { clear = false })
    onion.display_text("SEL jump  CANCEL back", 3, FOOT_Y, { clear = false })
    onion.display_commit()
end

-- Returns the page to jump to, or nil to just resume.
local function run_menu()
    save_bookmark()
    local entries = menu_entries()
    local cursor, top = 1, 1
    draw_menu(entries, cursor, top)
    local last = onion.buttons()
    while true do
        local buttons = onion.buttons()
        local moved = false
        if buttons.cancel and not last.cancel then
            return nil
        elseif buttons.select and not last.select then
            if cursor == 1 then return nil end
            return entries[cursor].p
        elseif buttons.down and not last.down then
            cursor = cursor + 1
            if cursor > #entries then cursor = 1 end
            moved = true
        elseif buttons.up and not last.up then
            cursor = cursor - 1
            if cursor < 1 then cursor = #entries end
            moved = true
        end
        if moved then
            if cursor < top then top = cursor end
            if cursor > top + MENU_ROWS - 1 then top = cursor - MENU_ROWS + 1 end
            draw_menu(entries, cursor, top)
        end
        last = buttons
        onion.sleep(60)
    end
end

-- Main loop ------------------------------------------------------------------

while true do
    local buttons = onion.buttons()
    if not (buttons.left or buttons.down or buttons.up or buttons.right or
            buttons.select or buttons.cancel) then
        break
    end
    onion.sleep(50)
end

draw_page(true)

local last = onion.buttons()
local held_dir = 0
local held_since = 0
local last_repeat = 0

while true do
    local buttons = onion.buttons()
    local now = onion.millis()
    local fwd = buttons.right or buttons.down
    local back = buttons.left or buttons.up
    local last_fwd = last.right or last.down
    local last_back = last.left or last.up

    if buttons.cancel and not last.cancel then
        save_bookmark()
        onion.release_display()
        return
    elseif buttons.select and not last.select then
        local target = run_menu()
        if target then
            page = target
            dirty = true
            save_bookmark()
        end
        draw_page(true)
        held_dir = 0
    elseif fwd and not last_fwd then
        turn(1)
        held_dir = 1
        held_since = now
        last_repeat = now
    elseif back and not last_back then
        turn(-1)
        held_dir = -1
        held_since = now
        last_repeat = now
    elseif held_dir == 1 and fwd then
        if now - held_since >= HOLD_MS and now - last_repeat >= REPEAT_MS then
            turn(1)
            last_repeat = now
        end
    elseif held_dir == -1 and back then
        if now - held_since >= HOLD_MS and now - last_repeat >= REPEAT_MS then
            turn(-1)
            last_repeat = now
        end
    else
        held_dir = 0
    end

    if dirty and onion.millis() - dirty_at >= SAVE_AFTER_MS then
        save_bookmark()
    end

    last = buttons
    onion.sleep(60)
end
